# Generated by Django 5.0.6 on 2024-06-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0002_alter_doctor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Email',
            field=models.CharField(default='nomail@gmail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(default=88877323273, max_length=200),
            preserve_default=False,
        ),
    ]
