# Generated by Django 5.0.6 on 2024-06-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0004_alter_doctor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Email',
            field=models.EmailField(default='nomail@gmail.com', max_length=200),
        ),
    ]
