# Generated by Django 5.0.6 on 2024-06-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0007_docdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='docdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='docdata',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
