# Generated by Django 5.0.6 on 2024-06-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0008_rename_username_doctor_name_remove_docdata_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Email',
            field=models.EmailField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
