# Generated by Django 5.0.6 on 2024-06-23 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0009_remove_doctor_id_alter_doctor_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
