# Generated by Django 5.0.6 on 2024-06-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0010_delete_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=200)),
                ('hospital', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
