# Generated by Django 5.0.6 on 2024-06-23 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0011_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='Name',
        ),
    ]
