# Generated by Django 5.0.6 on 2024-06-23 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0012_rename_name_doctor_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
