# Generated by Django 5.0.6 on 2024-08-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0014_doctor_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='docData',
        ),
        migrations.DeleteModel(
            name='Doctor_data',
        ),
        migrations.DeleteModel(
            name='usrData',
        ),
    ]
