# Generated by Django 5.0.6 on 2024-08-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0016_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usrdata',
            name='name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usrdata',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
