# Generated by Django 5.0.6 on 2024-08-30 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0018_alter_doctor_data_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_data',
            name='phone_number',
        ),
    ]
