# Generated by Django 5.0.6 on 2024-08-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0020_alter_doctor_data_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_appointment',
            name='problrm',
            field=models.CharField(max_length=150),
        ),
    ]
