# Generated by Django 5.0.6 on 2024-08-30 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0021_alter_user_appointment_problrm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_appointment',
            old_name='pemail',
            new_name='demail',
        ),
        migrations.RemoveField(
            model_name='user_appointment',
            name='dname',
        ),
        migrations.RemoveField(
            model_name='user_appointment',
            name='pmobile',
        ),
    ]
