# Generated by Django 5.0.6 on 2024-08-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0022_rename_pemail_user_appointment_demail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_appointment',
            name='gender',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
