# Generated by Django 5.0.6 on 2024-08-30 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0023_user_appointment_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_appointment',
            old_name='problrm',
            new_name='problem',
        ),
    ]
