# Generated by Django 5.0.6 on 2024-08-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0024_rename_problrm_user_appointment_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_appointment',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
