# Generated by Django 5.0.6 on 2024-09-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0026_user_appointment_pusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_appointment',
            name='demail',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user_appointment',
            name='pusername',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usrdata',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
