# Generated by Django 4.2.23 on 2025-10-04 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0030_doctor_map_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_appointment',
            name='pusername',
            field=models.CharField(max_length=20),
        ),
    ]
