# Generated by Django 4.2.23 on 2025-10-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0031_user_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_appointment',
            name='doctor_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_appointment',
            name='reply_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('ignored', 'Ignored'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user_appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
