# Generated by Django 4.2.23 on 2025-10-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0032_user_appointment_doctor_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_appointment',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user_appointment',
            name='blood_pressure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_appointment',
            name='booked_by',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='user_appointment',
            name='booking_type',
            field=models.CharField(choices=[('self', 'For Myself'), ('others', 'For Someone Else')], default='self', max_length=10),
        ),
        migrations.AddField(
            model_name='user_appointment',
            name='brain_tumor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_appointment',
            name='cancer_related',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_appointment',
            name='cholesterol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_appointment',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_appointment',
            name='heart_problem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_appointment',
            name='liver_problem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_appointment',
            name='patient_blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user_appointment',
            name='patient_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_appointment',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user_appointment',
            name='patient_height_cm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_appointment',
            name='patient_mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_appointment',
            name='patient_weight_kg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_appointment',
            name='symptoms',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user_appointment',
            name='ulcer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_appointment',
            name='pusername',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
